// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {models} from '../models';

export function CheckUpdate():Promise<void>;

export function Follow(arg1:string):Promise<string>;

export function GetConfig():Promise<data.Settings>;

export function GetFollowList():Promise<Array<data.FollowedStock>>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function GetVersionInfo():Promise<models.VersionInfo>;

export function UnFollow(arg1:string):Promise<string>;

export function UpdateConfig(arg1:data.Settings):Promise<string>;
