// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFollowList() {
  return window['go']['main']['App']['GetFollowList']();
}

export function GetStockList(arg1) {
  return window['go']['main']['App']['GetStockList'](arg1);
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function UnFollow(arg1) {
  return window['go']['main']['App']['UnFollow'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
